spring:
  application:
    name: account_microservice
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: postgres
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/microservices
    username: postgres
    password: postgres
    pool:
      enabled: true
      initial-size: 5
      max-size: 10
      max-idle-time: 10m

  kafka:
    consumer:
      group-id: account_microservice_group_id
    bootstrap-servers: localhost:9092

  flyway:
    baseline-on-migrate: true
    enabled: true
    user: "postgres"
    password: "postgres"
    url: "jdbc:postgresql://localhost:5432/microservices"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  otlp:
    metrics:
      export:
        url: http://host.docker.internal:4318/v1/metrics
        step: 1s
    tracing:
      endpoint: http://host.docker.internal:4318/v1/traces
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    io.r2dbc.postgresql.PARAM: debug
    io.r2dbc.postgresql.QUERY: debug


# https://localhost:8080/v3/api-docs.yaml
# http://localhost:8080/webjars/swagger-ui/index.html#/
springdoc:
  use-management-port: false

schedulers:
  outbox:
    enable: true
    initialDelayMillis: 3000
    fixedRate: 1000
    batchSize: 10

mongo:
  mongoURI: mongodb://mongo:mongo@localhost:27017/?maxPoolSize=20&w=majority

topics:
  accountCreated:
    name: account-created-v1
    partitions: 3
    replication: 1
  accountCreatedRetry:
    name: account-created-v1-retry
    partitions: 3
    replication: 1
  accountStatusChanged:
    name: account-status-changed-v1
    partitions: 3
    replication: 1
  accountStatusChangedRetry:
    name: account-status-changed-v1-retry
    partitions: 3
    replication: 1
  accountBalanceDeposited:
    name: account-balance-deposited-v1
    partitions: 3
    replication: 1
  accountBalanceDepositedRetry:
    name: account-balance-deposited-v1-retry
    partitions: 3
    replication: 1
  accountBalanceWithdraw:
    name: account-balance-withdraw-v1
    partitions: 3
    replication: 1
  accountBalanceWithdrawRetry:
    name: account-balance-withdraw-v1-retry
    partitions: 3
    replication: 1
  accountContactInfoChanged:
    name: account-contact-info-changed-v1
    partitions: 3
    replication: 1
  accountContactInfoChangedRetry:
    name: account-contact-info-changed-v1-retry
    partitions: 3
    replication: 1
  accountInfoUpdated:
    name: account-info-updated-v1
    partitions: 3
    replication: 1
  accountInfoUpdatedRetry:
    name: account-info-updated-v1-retry
    partitions: 3
    replication: 1
  deadLetterQueue:
    name: dead-letter-queue
    partitions: 3
    replication: 1

