spring:
  application:
    name: account_microservice
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: postgres
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/microservices
    username: postgres
    password: postgres
    pool:
      enabled: true
      initial-size: 5
      max-size: 10
      max-idle-time: 10m

  kafka:
    consumer:
      group-id: account_microservice_group_id
    bootstrap-servers: localhost:9092

  flyway:
    baseline-on-migrate: true
    enabled: true
    user: "postgres"
    password: "postgres"
    url: "jdbc:postgresql://localhost:5432/microservices"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 1s
    tracing:
      endpoint: http://localhost:4318/v1/traces
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    io.r2dbc.postgresql.PARAM: debug
    io.r2dbc.postgresql.QUERY: debug


# https://localhost:8080/v3/api-docs.yaml
# http://localhost:8080/webjars/swagger-ui/index.html#/
springdoc:
  use-management-port: false

schedulers:
  outbox:
    enable: false
    initialDelayMillis: 3000
    fixedRate: 1000
    batchSize: 10


topics:
  accountCreated:
    name: account-created
    partitions: 3
    replication: 1
  accountCreatedRetry:
    name: account-created-retry
    partitions: 3
    replication: 1
  deadLetterQueue:
    name: dead-letter-queue
    partitions: 3
    replication: 1