global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: [ 'otel-collector:8889' ]
  - job_name: 'account-microservice'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'host.docker.internal:2112' ]